services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak  # Creates the database automatically
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "22181:2181"
    networks:
      - microservices-net
  kafka:
    image: wurstmeister/kafka
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - microservices-net

  redis:
    image: redis
    container_name: ms_redis
    ports:
      - "6379:6379"
    networks:
      - microservices-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ms_keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KC_HOSTNAME: localhost
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
volumes:
  postgres_data: