spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-springboot-realm
          jwk-set-uri: http://localhost:9090/realms/ecommerce-springboot-realm/protocol/openid-connect/certs

server:
  port: 8070

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false # Disable Swagger UI in the service
  servers:
    - url: http://localhost:8080 # Gateway URL
      description: API Gateway