spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:org.example.order.kafka.OrderConfirmation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-springboot-realm
          jwk-set-uri: http://localhost:9090/realms/ecommerce-springboot-realm/protocol/openid-connect/certs


application:
  config:
    user-url: http://localhost:8090/api/v1/users
    product-url: http://localhost:8070/api/v1/products
    payment-url: http://localhost:8050/api/v1/payments

keycloak:
  auth-server-url: http://localhost:9090
  realm: ecommerce-springboot-realm
  client-id: order-service
  client-secret: tBP8FKOKTCIt4nhMmIiLSPA8TtCmkkYr

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false # Disable Swagger UI in the service
  servers:
    - url: http://localhost:8080 # Gateway URL
      description: API Gateway

server:
  port: 8060
