server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-springboot-realm
          jwk-set-uri: http://localhost:9090/realms/ecommerce-springboot-realm/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:9090
  realm: ecommerce-springboot-realm
  client-id: user-service
  client-secret: FE540DNHbyoTvL4KOQljzAwZaY4uYgxh
  user-role-name: USER

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false # Disable Swagger UI in the service
  servers:
    - url: http://localhost:8080 # Gateway URL
      description: API Gateway