### create payment
# need Authorization (Bearer Token) with Role 'ADMIN', 'USER'
POST http://localhost:8080/api/v1/payments
content-type: application/json

{
  "orderId": 1,
  "orderTrackingId": "TRC1738127273852",
  "totalAmount": 200.0,
  "paymentMethod": "CASH",
  "user": {
    "firstName": "Test",
    "lastName": "User",
    "email": "testuser@gmail.com"
  }
}