### create a new user
# need Authorization (Bearer Token) with Role 'ADMIN'
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com"
}

### get all users
# need Authorization (Bearer Token) with Role 'ADMIN'
GET http://localhost:8080/api/v1/users

### get user by id
# need Authorization (Bearer Token) with Role 'ADMIN'
GET http://localhost:8080/api/v1/users/1

### update user by id
# need Authorization (Bearer Token) with Role 'ADMIN'
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Moe",
  "email": "john.moe@example.com"
}

### delete user by id
# need Authorization (Bearer Token) with Role 'ADMIN'
DELETE http://localhost:8080/api/v1/users/1

### register user
# # no need Authenticatoin or Authorization
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "firstname": "Test",
  "lastname": "User",
  "email": "testuser@gmail.com",
  "username": "testuser",
  "password": "testpassword"
}

### login user
# no need Authenticatoin or Authorization
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}