### create category
# need Authorization (Bearer Token) with Role 'ADMIN'
POST http://localhost:8080/api/v1/category
content-type: application/json

{
  "name": "Clothing",
  "description": "Men's and women's apparel"
}

### get all categories
# need Authorization (Bearer Token) with Role 'ADMIN', 'USER'
GET http://localhost:8080/api/v1/categories

### get category by id
# need Authorization (Bearer Token) with Role 'ADMIN', 'USER'
GET http://localhost:8080/api/v1/categories/1

###update category by id
# need Authorization (Bearer Token) with Role 'ADMIN'
PUT http://localhost:8080/api/v1/categories/1
content-type: application/json

{
  "name": "Electronics",
  "description": "Devices, gadgets, and accessories all in one place"
}

### delete category by id
# need Authorization (Bearer Token) with Role 'ADMIN'
DELETE http://localhost:8080/api/v1/categories/5


### create product
# need Authorization (Bearer Token) with Role 'ADMIN'
POST http://localhost:8080/api/v1/products
content-type: application/json

{
  "name": "Men's Jacket",
  "description": "Waterproof winter jacket for men",
  "availableQuantity": 30,
  "price": 89.99,
  "categoryId": 3
}

### get all products
# need Authorization (Bearer Token) with Role 'ADMIN', 'USER'
GET http://localhost:8080/api/v1/products

### get product by id
# need Authorization (Bearer Token) with Role 'ADMIN', 'USER'
GET http://localhost:8080/api/v1/products/1

### update product by id
# need Authorization (Bearer Token) with Role 'ADMIN'
PUT http://localhost:8080/api/v1/products/1
content-type: application/json

{
  "name": "Smartphone",
  "description": "Latest Android smartphone with 128GB storage",
  "availableQuantity": 100,
  "price": 699.99,
  "categoryId": 1
}

### delete product by id
# need Authorization (Bearer Token) with Role 'ADMIN'
DELETE http://localhost:8080/api/v1/products/4

### purchase products
# need Authorization (Bearer Token) with Role 'ADMIN'
POST http://localhost:8080/api/v1/products/purchase
content-type: application/json

[
  {
    "productId": 1,
    "quantity": 2,
    "price": 89.99
  },
  {
    "productId": 2,
    "quantity": 1,
    "price": 89.50
  }
]
